sodists = Dict(
  "Chikkaballapur"   => 291,
  #"Raichur"          => 284,
  "Hassan"           => 289,
  #"Haveri"           => 279,
  "BBMP"             => 294,
  #"Vijayapura"       => 293,
  #"Bellary"          => 274,
  #"Koppal"           => 282,
  "Bangalore Urban"  => 265,
  "Kolar"            => 277,
  "Chamarajanagar"   => 271,
  #"Uttar Kannada"    => 281,
  "Tumkur"           => 288,
  #"Dharwad"          => 278,
  #"Dakshina Kannada" => 269,
  "Bangalore Rural"  => 276,
  #"Davanagere"       => 275,
  #"Chikamagalur"     => 273,
  #"Gulbarga"         => 267,
  #"Bagalkot"         => 270,
  #"Gadag"            => 280,
  "Mysore"           => 266,
  #"Udupi"            => 286,
  "Ramanagara"       => 292,
  #"Belgaum"          => 264,
  #"Bidar"            => 272,
  "Chitradurga"      => 268,
  #"Yadgir"           => 285,
  #"Shimoga"          => 287,
  "Mandya"           => 290,

  #"Kasaragod"        => 295,
  #"Kannur"           => 297,
  #"Kozhikode"        => 305,
  #"Wayanad"          => 299,
  #"Malappuram"       => 302,

  #"Nilgiris"         => 577,
  #"Erode"            => 563,
  "Dharmapuri"       => 566,
  "Krishnagiri"      => 562,
  #"Salem"            => 545,
  #"Namakkal"         => 558,
  #"Tiruppur"         => 568,
  #"Tirupattur"       => 550,
  #"Coimbatore"       => 539,
  
  "Chittoor"         => 10,
  #"Anantapur"        => 9,
  #"Kurnool"          => 7,
  #"Kadapa"           => 6,

  #"North Goa"        => 151,
  #"South Goa"        => 152
)
